name: kubectl setup

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: actions-hub/kubectl@1.24.0
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: get pods

      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube

      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Show running pods
        run: kubectl get pods -A
