name: Show Kubernetes Pods and Services

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube

      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Show running pods
        run: kubectl get pods -A

      - name: Show running services
        run: kubectl get services -A
