name: kubectl setup

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: actions-hub/kubectl@v1.30.3
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      # - name: Create kubeconfig directory
      #   run: mkdir -p $HOME/.kube

      # - name: Set KUBECONFIG
      #   run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # - name: Show running pods
      #   run: kubectl get pods -A
